#!/usr/bin/env bash
set -e

exit_now () {
	echo "Process cancellation requested. Exiting."
	exit
}

trap exit_now TERM
trap exit_now INT
trap exit_now KILL

while [[ 1 ]] 
do
	curl -k "https://www.duckdns.org/update?domains=$DUCKDNS_DOMAINS&token=$DUCKDNS_TOKEN&ip="
	sleep $DUCKDNS_UPDATE_FREQUENCY_IN_SECONDS
done