#!/usr/bin/env bash
set -e

exit_now () {
	echo "Process cancellation requested. Exiting."
	exit
}

trap exit_now TERM
trap exit_now INT
trap exit_now KILL

while [[ 1 ]] 
do
	echo 'Updating domains...'
	curl -ksq "https://www.duckdns.org/update?domains=$DUCKDNS_DOMAINS&token=$DUCKDNS_TOKEN&ip="
	result=$?
	echo 'Domains updated successful.'
	if [[ -n "$HEALTHCHECK_URL" ]]; then
		if [[ $result -eq 0 ]]; then
			curl -ksq $HEALTHCHECK_URL
			echo 'Successfully notified monitor.'
		fi
	fi

	sleep $DUCKDNS_UPDATE_FREQUENCY_IN_SECONDS
done